trigger: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest

resources:
  repositories:
  - repository: Shared
    type: git
    name: DX/Shared

steps:

- template: templates/build/build_package_template_v1.yml@Shared
  parameters:
    projectName: Perplex.ContentBlocksToBlockList
